# Site settings
title: Naresh Nindra
subtitle: Exploring and Simplifying Complexity
email: msg4naresh@gmail.com
description: "Exploring and Simplifying Complexity"
baseurl: ""
url: "https://NareshNindra.github.io"
twitter_username: nareshnindra
github_username: nareshnindra

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]


